spring.autoconfigure.exclude=
spring.datasource.url=${QUEUE_DB_URL:jdbc:h2:file:./data/queue;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=sa
spring.datasource.password=${QUEUE_DB_PASSWORD:}
spring.sql.init.mode=always
